### RollNo:CO2105 & Name:Sandhya Raghunath Magadum

In [1]:
import pandas as pd
import numpy as np

## 1.World Cup Matches

In [2]:
#using file name
df = pd.read_csv( 'WorldCupMatches.csv')
df

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#using file path
df = pd.read_csv("D:/machine learning/WorldCupMatches.csv")
df

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 2 liver_synthetic

In [5]:
#using file name
df = pd.read_csv('liver_synthetic.csv')
df

     Age  Gender   TB    DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     55    Male  5.8  1.57      559   243   157  7.1  3.9  0.41             1
1     18    Male  5.8  0.89       74   204    72  6.9  2.8  1.07             1
2     75    Male  4.0  0.65      682   128   319  7.1  1.1  0.99             0
3     64    Male  2.0  0.55      728    29   252  7.8  4.9   NaN             1
4     24    Male  3.2  1.54      348   270   339  6.7  2.0  1.05             0
..   ...     ...  ...   ...      ...   ...   ...  ...  ...   ...           ...
198   47    Male  6.9  1.31      573    68   318  5.8  2.7  1.37             1
199   35    Male  0.2  1.18      582    81    17  8.8  3.4  0.68             1
200   86  Female  2.3  1.02      537   265   116  7.2  1.8  0.61             0
201   86  Female  2.3  1.02      537   265   116  7.2  1.8  0.61             0
202   36    Male  2.1  1.20      177   218    29  4.9  2.3  0.76             1

[203 rows x 11 columns]

In [6]:
#using file path
df = pd.read_excel(r"D:\fifa1\liver_synthetic.xlsx")
df

     Age  Gender   TB    DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     55    Male  5.8  1.57      559   243   157  7.1  3.9  0.41             1
1     18    Male  5.8  0.89       74   204    72  6.9  2.8  1.07             1
2     75    Male  4.0  0.65      682   128   319  7.1  1.1  0.99             0
3     64    Male  2.0  0.55      728    29   252  7.8  4.9   NaN             1
4     24    Male  3.2  1.54      348   270   339  6.7  2.0  1.05             0
..   ...     ...  ...   ...      ...   ...   ...  ...  ...   ...           ...
198   47    Male  6.9  1.31      573    68   318  5.8  2.7  1.37             1
199   35    Male  0.2  1.18      582    81    17  8.8  3.4  0.68             1
200   86  Female  2.3  1.02      537   265   116  7.2  1.8  0.61             0
201   86  Female  2.3  1.02      537   265   116  7.2  1.8  0.61             0
202   36    Male  2.1  1.20      177   218    29  4.9  2.3  0.76             1

[203 rows x 11 columns]

## 3 Advertising

In [7]:
#using file name
df = pd.read_csv('Advertising.csv')
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [8]:
#using file path
df = pd.read_csv(r"D:/fifa1/Advertising.csv")
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

## 4 Boston

In [9]:
#using file name
df = pd.read_csv('Boston.csv')
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [10]:
#using file path
df = pd.read_csv("D:/fifa1/Boston.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

## 5 claimants sample

In [11]:
#using file name
df = pd.read_csv('claimants sample.csv')
df

   CASENUM  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS  ATTORNEY
0        5       0       1.0         0    50.0  34.940         0
1        3       1       0.0         0    18.0   0.891         1
2       66       0       1.0         0     5.0   0.330         1
3       70       1       1.0         1    31.0   0.037         0
4       96       0       1.0         0    30.0     NaN         1
5       97       1       1.0         0    35.0   0.309         0
6       10       0       NaN         0     9.0   3.538         0
7       36       1       NaN         0    34.0   4.881         0
8       51       1       1.0         0    60.0   0.874         1
9       55       1       1.0         0     NaN   0.350         1

In [12]:
#using file path
df = pd.read_csv("D:/fifa1/claimants sample.csv")
df

   CASENUM  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS  ATTORNEY
0        5       0       1.0         0    50.0  34.940         0
1        3       1       0.0         0    18.0   0.891         1
2       66       0       1.0         0     5.0   0.330         1
3       70       1       1.0         1    31.0   0.037         0
4       96       0       1.0         0    30.0     NaN         1
5       97       1       1.0         0    35.0   0.309         0
6       10       0       NaN         0     9.0   3.538         0
7       36       1       NaN         0    34.0   4.881         0
8       51       1       1.0         0    60.0   0.874         1
9       55       1       1.0         0     NaN   0.350         1

## 6 claimants

In [13]:
#using file name
df = pd.read_csv('claimants.csv')
df

      CASENUM  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS  ATTORNEY
0           5     0.0       1.0       0.0    50.0  34.940         0
1           3     1.0       0.0       0.0    18.0   0.891         1
2          66     0.0       1.0       0.0     5.0   0.330         1
3          70     0.0       1.0       1.0    31.0   0.037         0
4          96     0.0       1.0       0.0    30.0   0.038         1
...       ...     ...       ...       ...     ...     ...       ...
1335    34100     0.0       1.0       0.0     NaN   0.576         1
1336    34110     1.0       1.0       0.0    46.0   3.705         0
1337    34113     1.0       1.0       0.0    39.0   0.099         1
1338    34145     1.0       0.0       0.0     8.0   3.177         0
1339    34153     1.0       1.0       0.0    30.0   0.688         1

[1340 rows x 7 columns]

In [14]:
#using file path
df = pd.read_csv("D:/fifa1/claimants.csv")
df

      CASENUM  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS  ATTORNEY
0           5     0.0       1.0       0.0    50.0  34.940         0
1           3     1.0       0.0       0.0    18.0   0.891         1
2          66     0.0       1.0       0.0     5.0   0.330         1
3          70     0.0       1.0       1.0    31.0   0.037         0
4          96     0.0       1.0       0.0    30.0   0.038         1
...       ...     ...       ...       ...     ...     ...       ...
1335    34100     0.0       1.0       0.0     NaN   0.576         1
1336    34110     1.0       1.0       0.0    46.0   3.705         0
1337    34113     1.0       1.0       0.0    39.0   0.099         1
1338    34145     1.0       0.0       0.0     8.0   3.177         0
1339    34153     1.0       1.0       0.0    30.0   0.688         1

[1340 rows x 7 columns]

## 7 gene_expression

In [15]:
#using file name
df = pd.read_csv('gene_expression.csv')
df

      Gene One  Gene Two  Cancer Present
0          4.3       3.9               1
1          2.5       6.3               0
2          5.7       3.9               1
3          6.1       6.2               0
4          7.4       3.4               1
...        ...       ...             ...
2995       5.0       6.5               1
2996       3.4       6.6               0
2997       2.7       6.5               0
2998       3.3       5.6               0
2999       4.6       8.2               0

[3000 rows x 3 columns]

In [16]:
#using file path
df = pd.read_csv("D:/fifa1/gene_expression.csv")
df

      Gene One  Gene Two  Cancer Present
0          4.3       3.9               1
1          2.5       6.3               0
2          5.7       3.9               1
3          6.1       6.2               0
4          7.4       3.4               1
...        ...       ...             ...
2995       5.0       6.5               1
2996       3.4       6.6               0
2997       2.7       6.5               0
2998       3.3       5.6               0
2999       4.6       8.2               0

[3000 rows x 3 columns]

## 8 hearing_test

In [17]:
#using file name
df = pd.read_csv('hearing_test.csv')
df

       age  physical_score  test_result
0     33.0            40.7            1
1     50.0            37.2            1
2     52.0            24.7            0
3     56.0            31.0            0
4     35.0            42.9            1
...    ...             ...          ...
4995  73.0             3.9            0
4996  57.0            33.9            1
4997  49.0            34.5            1
4998  38.0            46.4            1
4999  48.0            38.5            1

[5000 rows x 3 columns]

In [18]:
#using file path
df = pd.read_csv("D:/fifa1/hearing_test.csv")
df

       age  physical_score  test_result
0     33.0            40.7            1
1     50.0            37.2            1
2     52.0            24.7            0
3     56.0            31.0            0
4     35.0            42.9            1
...    ...             ...          ...
4995  73.0             3.9            0
4996  57.0            33.9            1
4997  49.0            34.5            1
4998  38.0            46.4            1
4999  48.0            38.5            1

[5000 rows x 3 columns]

## 9 homeprices

In [19]:
#using file name
df = pd.read_csv('homeprices.csv')
df

         town  area    price
0     Chennai  2600  5500000
1     Chennai  3000  5650000
2     Chennai  3200  6100000
3     Chennai  3600  6800000
4   Bangalore  2600  5850000
5   Bangalore  2800  6150000
6   Bangalore  3300  6500000
7   Bangalore  3600  7100000
8   Hyderabad  2600  5750000
9   Hyderabad  2900  6000000
10  Hyderabad  3100  6200000
11  Hyderabad  3600  6950000

In [20]:
#using file path
df = pd.read_csv("D:/fifa1/homeprices.csv")
df

         town  area    price
0     Chennai  2600  5500000
1     Chennai  3000  5650000
2     Chennai  3200  6100000
3     Chennai  3600  6800000
4   Bangalore  2600  5850000
5   Bangalore  2800  6150000
6   Bangalore  3300  6500000
7   Bangalore  3600  7100000
8   Hyderabad  2600  5750000
9   Hyderabad  2900  6000000
10  Hyderabad  3100  6200000
11  Hyderabad  3600  6950000

## 10 liver_synthetic

In [21]:
#using file name
df = pd.read_csv('liver_synthetic.csv')
df

     Age  Gender   TB    DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     55    Male  5.8  1.57      559   243   157  7.1  3.9  0.41             1
1     18    Male  5.8  0.89       74   204    72  6.9  2.8  1.07             1
2     75    Male  4.0  0.65      682   128   319  7.1  1.1  0.99             0
3     64    Male  2.0  0.55      728    29   252  7.8  4.9   NaN             1
4     24    Male  3.2  1.54      348   270   339  6.7  2.0  1.05             0
..   ...     ...  ...   ...      ...   ...   ...  ...  ...   ...           ...
198   47    Male  6.9  1.31      573    68   318  5.8  2.7  1.37             1
199   35    Male  0.2  1.18      582    81    17  8.8  3.4  0.68             1
200   86  Female  2.3  1.02      537   265   116  7.2  1.8  0.61             0
201   86  Female  2.3  1.02      537   265   116  7.2  1.8  0.61             0
202   36    Male  2.1  1.20      177   218    29  4.9  2.3  0.76             1

[203 rows x 11 columns]

In [22]:
#using file path
df = pd.read_csv("D:/fifa1/liver_synthetic.csv")
df

     Age  Gender   TB    DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     55    Male  5.8  1.57      559   243   157  7.1  3.9  0.41             1
1     18    Male  5.8  0.89       74   204    72  6.9  2.8  1.07             1
2     75    Male  4.0  0.65      682   128   319  7.1  1.1  0.99             0
3     64    Male  2.0  0.55      728    29   252  7.8  4.9   NaN             1
4     24    Male  3.2  1.54      348   270   339  6.7  2.0  1.05             0
..   ...     ...  ...   ...      ...   ...   ...  ...  ...   ...           ...
198   47    Male  6.9  1.31      573    68   318  5.8  2.7  1.37             1
199   35    Male  0.2  1.18      582    81    17  8.8  3.4  0.68             1
200   86  Female  2.3  1.02      537   265   116  7.2  1.8  0.61             0
201   86  Female  2.3  1.02      537   265   116  7.2  1.8  0.61             0
202   36    Male  2.1  1.20      177   218    29  4.9  2.3  0.76             1

[203 rows x 11 columns]

## 11 liver

In [23]:
#using file name
df = pd.read_csv('liver.csv')
df

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]

In [24]:
#using file path
df = pd.read_csv("D:/fifa1/liver.csv")
df

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]

## 12 mouse_viral_study

In [25]:
#using file name
df = pd.read_csv('mouse_viral_study.csv')
df

     Med_1_mL  Med_2_mL  Virus Present
0    6.508231  8.582531              0
1    4.126116  3.073459              1
2    6.427870  6.369758              0
3    3.672953  4.905215              1
4    1.580321  2.440562              1
..        ...       ...            ...
395  2.884122  3.271748              1
396  7.290855  9.488672              0
397  7.895325  8.272529              0
398  2.690592  2.674979              1
399  7.587821  9.473968              0

[400 rows x 3 columns]

In [26]:
#using file path
df = pd.read_csv("D:/fifa1/mouse_viral_study.csv")
df

     Med_1_mL  Med_2_mL  Virus Present
0    6.508231  8.582531              0
1    4.126116  3.073459              1
2    6.427870  6.369758              0
3    3.672953  4.905215              1
4    1.580321  2.440562              1
..        ...       ...            ...
395  2.884122  3.271748              1
396  7.290855  9.488672              0
397  7.895325  8.272529              0
398  2.690592  2.674979              1
399  7.587821  9.473968              0

[400 rows x 3 columns]

## 13 mushrooms

In [27]:
#using file name
df = pd.read_csv('mushrooms.csv')
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

In [28]:
#using file path
df = pd.read_csv("D:/fifa1/mushrooms.csv")
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

## 14 penguins_size

In [29]:
#using file name
df = pd.read_csv('penguins_size.csv')
df

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [30]:
#using file path
df = pd.read_csv("D:/fifa1/penguins_size.csv")
df

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

## 15 stroke prediction

In [31]:
#using file name
df = pd.read_csv('stroke prediction.csv')
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,30669,Male,3.0,0,0,No,children,Rural,95.12,18.0,NaN,0
1,30468,Male,58.0,1,0,Yes,Private,Urban,87.96,39.2,never smoked,0
2,16523,Female,8.0,0,0,No,Private,Urban,110.89,17.6,NaN,0
3,56543,Female,70.0,0,0,Yes,Private,Rural,69.04,35.9,formerly smoked,0
4,46136,Male,14.0,0,0,No,Never_worked,Rural,161.28,19.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
43395,56196,Female,10.0,0,0,No,children,Urban,58.64,20.4,never smoked,0
43396,5450,Female,56.0,0,0,Yes,Govt_job,Urban,213.61,55.4,formerly smoked,0
43397,28375,Female,82.0,1,0,Yes,Private,Urban,91.94,28.9,formerly smoked,0
43398,27973,Male,40.0,0,0,Yes,Private,Urban,99.16,33.2,never smoked,0
43399,36271,Female,82.0,0,0,Yes,Private,Urban,79.48,20.6,never smoked,0

In [32]:
#using file path
df = pd.read_csv("D:/fifa1/stroke prediction.csv")
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,30669,Male,3.0,0,0,No,children,Rural,95.12,18.0,NaN,0
1,30468,Male,58.0,1,0,Yes,Private,Urban,87.96,39.2,never smoked,0
2,16523,Female,8.0,0,0,No,Private,Urban,110.89,17.6,NaN,0
3,56543,Female,70.0,0,0,Yes,Private,Rural,69.04,35.9,formerly smoked,0
4,46136,Male,14.0,0,0,No,Never_worked,Rural,161.28,19.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
43395,56196,Female,10.0,0,0,No,children,Urban,58.64,20.4,never smoked,0
43396,5450,Female,56.0,0,0,Yes,Govt_job,Urban,213.61,55.4,formerly smoked,0
43397,28375,Female,82.0,1,0,Yes,Private,Urban,91.94,28.9,formerly smoked,0
43398,27973,Male,40.0,0,0,Yes,Private,Urban,99.16,33.2,never smoked,0
43399,36271,Female,82.0,0,0,Yes,Private,Urban,79.48,20.6,never smoked,0

## 16 tips

In [33]:
#using file name
df = pd.read_csv('tips.csv')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [34]:
#using file path
df = pd.read_csv("D:/fifa1/tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## 17 titanic

In [35]:
#using file name
df = pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [36]:
#using file path
df = pd.read_csv("D:/fifa1/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## 18 train_test

In [37]:
#using file name
df = pd.read_csv('train_test.csv')
df

    advitise  sales
0          2     15
1          3     17
2          7     12
3          9      8
4          4      3
5          5      4
6         11      6
7         13      8
8         10     13
9          6     17
10        15      4
11        19      3
12         2      8
13         3      1
14         6     14
15         9     17
16         2     14
17         8     16
18         1     11
19         0     12

In [38]:
#using file path
df = pd.read_csv("D:/fifa1/train_test.csv")
df

    advitise  sales
0          2     15
1          3     17
2          7     12
3          9      8
4          4      3
5          5      4
6         11      6
7         13      8
8         10     13
9          6     17
10        15      4
11        19      3
12         2      8
13         3      1
14         6     14
15         9     17
16         2     14
17         8     16
18         1     11
19         0     12

## 19 Bahaman

In [39]:
#using file name 
df = pd.read_excel('Bahaman.xlsx')
df

     Defective     Country
0            0       India
1            0       India
2            0       India
3            0       India
4            1       India
..         ...         ...
795          0  Bangladesh
796          0  Bangladesh
797          1  Bangladesh
798          0  Bangladesh
799          0  Bangladesh

[800 rows x 2 columns]

In [40]:
#using file path
df = pd.read_excel("D:/fifa1/Bahaman.xlsx")
df

     Defective     Country
0            0       India
1            0       India
2            0       India
3            0       India
4            1       India
..         ...         ...
795          0  Bangladesh
796          0  Bangladesh
797          1  Bangladesh
798          0  Bangladesh
799          0  Bangladesh

[800 rows x 2 columns]

## 20 Bolt diameter

In [41]:
#using file name 
df = pd.read_excel('Bolt diameter.xlsx')
df

    Diameter
0      11.27
1      12.06
2      12.15
3       9.89
4      10.82
5      13.53
6      10.83
7       8.87
8      11.14
9       9.71
10     11.88
11      9.53
12     13.17
13     10.54
14     11.25
15     10.84
16     11.29
17     10.54
18     10.74
19     10.93

In [42]:
#using file path
df = pd.read_excel("D:/fifa1/Bolt diameter.xlsx")
df

    Diameter
0      11.27
1      12.06
2      12.15
3       9.89
4      10.82
5      13.53
6      10.83
7       8.87
8      11.14
9       9.71
10     11.88
11      9.53
12     13.17
13     10.54
14     11.25
15     10.84
16     11.29
17     10.54
18     10.74
19     10.93

## 21 Contract Renewal

In [43]:
#using file name 
df = pd.read_excel('Contract Renewal.xlsx')
df

     SupplierA  SupplierB  SupplierC
0         6.15       7.87       7.41
1         6.22       5.21       3.61
2         6.76       7.94       7.23
3         4.29       7.36       5.53
4         7.08       6.17       3.97
..         ...        ...        ...
115       5.85       4.53       4.27
116       5.04       8.06       6.39
117       5.68       7.14       4.60
118       4.77       4.84       6.15
119       3.57       4.55       5.28

[120 rows x 3 columns]

In [44]:
#using file path
df = pd.read_excel("D:/fifa1/Contract Renewal.xlsx")
df

     SupplierA  SupplierB  SupplierC
0         6.15       7.87       7.41
1         6.22       5.21       3.61
2         6.76       7.94       7.23
3         4.29       7.36       5.53
4         7.08       6.17       3.97
..         ...        ...        ...
115       5.85       4.53       4.27
116       5.04       8.06       6.39
117       5.68       7.14       4.60
118       4.77       4.84       6.15
119       3.57       4.55       5.28

[120 rows x 3 columns]

## 22 Fabric data

In [45]:
#using file name 
df = pd.read_excel('Fabric data.xlsx')
df

    Fabric_length
0           151.2
1           160.3
2           147.5
3           149.2
4           159.2
5           155.6
6           148.1
7           154.8
8           156.8
9           167.5
10          164.5
11          147.9
12          154.1
13          159.4
14          147.5
15          148.2
16          154.2
17          148.1
18          163.1
19          155.2
20          154.6
21          155.4
22          158.2
23          157.6
24          158.4

In [46]:
#using file path
df = pd.read_excel("D:/fifa1/Fabric data.xlsx")
df

    Fabric_length
0           151.2
1           160.3
2           147.5
3           149.2
4           159.2
5           155.6
6           148.1
7           154.8
8           156.8
9           167.5
10          164.5
11          147.9
12          154.1
13          159.4
14          147.5
15          148.2
16          154.2
17          148.1
18          163.1
19          155.2
20          154.6
21          155.4
22          158.2
23          157.6
24          158.4

## 23 JohnyTalkers

In [47]:
#using file name 
df = pd.read_excel('JohnyTalkers.xlsx')
df

        Person            Drinks
0       Adults  Did Not Purchase
1       Adults  Did Not Purchase
2       Adults  Did Not Purchase
3       Adults  Did Not Purchase
4       Adults  Did Not Purchase
...        ...               ...
1215  Children  Did Not Purchase
1216  Children  Did Not Purchase
1217  Children  Did Not Purchase
1218  Children  Did Not Purchase
1219  Children         Purchased

[1220 rows x 2 columns]

In [48]:
#using file path
df = pd.read_excel("D:/fifa1/JohnyTalkers.xlsx")
df

        Person            Drinks
0       Adults  Did Not Purchase
1       Adults  Did Not Purchase
2       Adults  Did Not Purchase
3       Adults  Did Not Purchase
4       Adults  Did Not Purchase
...        ...               ...
1215  Children  Did Not Purchase
1216  Children  Did Not Purchase
1217  Children  Did Not Purchase
1218  Children  Did Not Purchase
1219  Children         Purchased

[1220 rows x 2 columns]